server:
  port: 8080
  servlet:
    context-path: /api
spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/passworder?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    username: simon290344@gmail.com
    password: dvvp swlb scae bkks
    port: 587
    protocol: smtps
    debug: true
  mime:
    address:
      strict: false